version: "3"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    container_name: "kibana"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
        - "5043:5043"


