version: "3"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: "es"
    volumes:
      - ./es.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
